/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Control.History_db_Controller;
import Control.ImageController;
import Model.HistoryModel;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Edward
 */
public class HistoryList extends javax.swing.JPanel {

    /**
     * Creates new form HistoryList
     */
    public HistoryList() {
        initComponents();
        isiHistoryCart();
    }
    
    HistoryModel historyModel = new HistoryModel(null, 0, null);
    History_db_Controller db = new History_db_Controller();
    ImageController ic = new ImageController();
    DecimalFormat df = new DecimalFormat("#,##0.00");
    
    public void isiHistoryCart() {
        historyModel.listHistory.clear();
        db.selectListHistory(historyModel);
        String[][] dataTabel = new String [historyModel.listHistory.size()][4];
        
        int i = 0;
        
        for (HistoryModel history : historyModel.listHistory) {
            dataTabel[i][0] = "" + (i + 1);
            dataTabel[i][1] = String.valueOf(history.getTanggal());
            dataTabel[i][2] = df.format(history.getTotalHargaCart());
            dataTabel[i][3] = history.getAlamat();
            
            i++;
        }
        
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
                dataTabel,
                new String[]{
                    "No.", "Tanggal", "Total Harga", "Alamat"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCustom2 = new View.Custom.JPanelCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jPanelCustom1 = new View.Custom.JPanelCustom();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 150, 202));
        jLabel1.setText("History");

        jPanelCustom2.setBackground(new java.awt.Color(245, 141, 63));
        jPanelCustom2.setRadiusBottomLeft(20);
        jPanelCustom2.setRadiusBottomRight(20);
        jPanelCustom2.setRadiusTopLeft(20);
        jPanelCustom2.setRadiusTopRight(20);

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        historyTable.setBackground(new java.awt.Color(255, 255, 255));
        historyTable.setForeground(new java.awt.Color(0, 0, 0));
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Tanggal", "Total Harga", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(historyTable);

        jPanelCustom1.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom1.setRadiusBottomLeft(40);
        jPanelCustom1.setRadiusBottomRight(40);
        jPanelCustom1.setRadiusTopLeft(40);
        jPanelCustom1.setRadiusTopRight(40);
        jPanelCustom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPEN");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCustom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom1MouseClicked
        int row = historyTable.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select item dalam history terlebih dahulu!", "SELECT HISTORY", JOptionPane.ERROR_MESSAGE);
        }
        
        HistoryModel history = historyModel.listHistory.get(row);
        Timestamp tanggal = history.getTanggal();
        String alamat = history.getAlamat();
        double totalHargaCart = history.getTotalHargaCart();

        
        HistoryDetail historyDetail = new HistoryDetail();
        historyDetail.isiHistoryDetail(historyModel, tanggal, alamat, totalHargaCart);
        
        MainMenu.panelUtama.removeAll();
        MainMenu.panelUtama.add(historyDetail);
        MainMenu.panelUtama.repaint();
        MainMenu.panelUtama.revalidate();
        
    }//GEN-LAST:event_jPanelCustom1MouseClicked

    private void jPanelCustom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom1MouseEntered
        ic.backgroundEntered(jPanelCustom1);
    }//GEN-LAST:event_jPanelCustom1MouseEntered

    private void jPanelCustom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom1MouseExited
        ic.backgroundExited(jPanelCustom1);
    }//GEN-LAST:event_jPanelCustom1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private View.Custom.JPanelCustom jPanelCustom1;
    private View.Custom.JPanelCustom jPanelCustom2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
