/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ImageController;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Edward
 */
public class MainMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCustom1 = new View.Custom.JPanelCustom();
        jLabel2 = new javax.swing.JLabel();
        panelHome = new View.Custom.JPanelCustom();
        panelTandaWarna = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        panelRunning = new View.Custom.JPanelCustom();
        panelTandaWarna1 = new javax.swing.JPanel();
        running = new javax.swing.JLabel();
        panelPantofel = new View.Custom.JPanelCustom();
        panelTandaWarna2 = new javax.swing.JPanel();
        pantofel = new javax.swing.JLabel();
        panelSneakers = new View.Custom.JPanelCustom();
        panelTandaWarna3 = new javax.swing.JPanel();
        sneakers = new javax.swing.JLabel();
        panelFlatshoes = new View.Custom.JPanelCustom();
        panelTandaWarna4 = new javax.swing.JPanel();
        flatshoes = new javax.swing.JLabel();
        panelHeels = new View.Custom.JPanelCustom();
        panelTandaWarna5 = new javax.swing.JPanel();
        heels = new javax.swing.JLabel();
        jPanelCustom8 = new View.Custom.JPanelCustom();
        jLabel5 = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelUtama = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        homePage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCustom1 = new View.Custom.JLabelCustom();
        jPanel2 = new javax.swing.JPanel();
        jPanelCustom2 = new View.Custom.JPanelCustom();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCustom3 = new View.Custom.JPanelCustom();
        jLabel7 = new javax.swing.JLabel();
        jPanelCustom4 = new View.Custom.JPanelCustom();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelCustom5 = new View.Custom.JPanelCustom();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelCustom6 = new View.Custom.JPanelCustom();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelCustom7 = new View.Custom.JPanelCustom();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKiri.setBackground(new java.awt.Color(255, 255, 255));
        panelKiri.setPreferredSize(new java.awt.Dimension(222, 720));

        jLabel1.setFont(new java.awt.Font("STCaiyun", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 43, 78));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buatmain.png"))); // NOI18N

        jPanelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom1.setRadiusBottomLeft(20);
        jPanelCustom1.setRadiusBottomRight(20);
        jPanelCustom1.setRadiusTopLeft(20);
        jPanelCustom1.setRadiusTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 150, 202));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setRadiusBottomLeft(10);
        panelHome.setRadiusBottomRight(10);
        panelHome.setRadiusTopLeft(10);
        panelHome.setRadiusTopRight(10);
        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHomeMouseExited(evt);
            }
        });

        panelTandaWarna.setBackground(new java.awt.Color(25, 150, 202));
        panelTandaWarna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTandaWarnaLayout = new javax.swing.GroupLayout(panelTandaWarna);
        panelTandaWarna.setLayout(panelTandaWarnaLayout);
        panelTandaWarnaLayout.setHorizontalGroup(
            panelTandaWarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelTandaWarnaLayout.setVerticalGroup(
            panelTandaWarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homeButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(25, 150, 202));
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTandaWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTandaWarna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelRunning.setBackground(new java.awt.Color(255, 255, 255));
        panelRunning.setRadiusBottomLeft(10);
        panelRunning.setRadiusBottomRight(10);
        panelRunning.setRadiusTopLeft(10);
        panelRunning.setRadiusTopRight(10);
        panelRunning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRunningMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRunningMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRunningMouseExited(evt);
            }
        });

        panelTandaWarna1.setBackground(new java.awt.Color(25, 150, 202));
        panelTandaWarna1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTandaWarna1Layout = new javax.swing.GroupLayout(panelTandaWarna1);
        panelTandaWarna1.setLayout(panelTandaWarna1Layout);
        panelTandaWarna1Layout.setHorizontalGroup(
            panelTandaWarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelTandaWarna1Layout.setVerticalGroup(
            panelTandaWarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        running.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        running.setForeground(new java.awt.Color(25, 150, 202));
        running.setText("Running");
        running.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRunningLayout = new javax.swing.GroupLayout(panelRunning);
        panelRunning.setLayout(panelRunningLayout);
        panelRunningLayout.setHorizontalGroup(
            panelRunningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRunningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTandaWarna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(running, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRunningLayout.setVerticalGroup(
            panelRunningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTandaWarna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(running, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelPantofel.setBackground(new java.awt.Color(255, 255, 255));
        panelPantofel.setRadiusBottomLeft(10);
        panelPantofel.setRadiusBottomRight(10);
        panelPantofel.setRadiusTopLeft(10);
        panelPantofel.setRadiusTopRight(10);
        panelPantofel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPantofelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPantofelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPantofelMouseExited(evt);
            }
        });

        panelTandaWarna2.setBackground(new java.awt.Color(25, 150, 202));
        panelTandaWarna2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTandaWarna2Layout = new javax.swing.GroupLayout(panelTandaWarna2);
        panelTandaWarna2.setLayout(panelTandaWarna2Layout);
        panelTandaWarna2Layout.setHorizontalGroup(
            panelTandaWarna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelTandaWarna2Layout.setVerticalGroup(
            panelTandaWarna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pantofel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pantofel.setForeground(new java.awt.Color(25, 150, 202));
        pantofel.setText("Pantofel");
        pantofel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelPantofelLayout = new javax.swing.GroupLayout(panelPantofel);
        panelPantofel.setLayout(panelPantofelLayout);
        panelPantofelLayout.setHorizontalGroup(
            panelPantofelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantofelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTandaWarna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pantofel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPantofelLayout.setVerticalGroup(
            panelPantofelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTandaWarna2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pantofel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelSneakers.setBackground(new java.awt.Color(255, 255, 255));
        panelSneakers.setRadiusBottomLeft(10);
        panelSneakers.setRadiusBottomRight(10);
        panelSneakers.setRadiusTopLeft(10);
        panelSneakers.setRadiusTopRight(10);
        panelSneakers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSneakersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSneakersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSneakersMouseExited(evt);
            }
        });

        panelTandaWarna3.setBackground(new java.awt.Color(25, 150, 202));
        panelTandaWarna3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTandaWarna3Layout = new javax.swing.GroupLayout(panelTandaWarna3);
        panelTandaWarna3.setLayout(panelTandaWarna3Layout);
        panelTandaWarna3Layout.setHorizontalGroup(
            panelTandaWarna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelTandaWarna3Layout.setVerticalGroup(
            panelTandaWarna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        sneakers.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        sneakers.setForeground(new java.awt.Color(25, 150, 202));
        sneakers.setText("Sneakers");
        sneakers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelSneakersLayout = new javax.swing.GroupLayout(panelSneakers);
        panelSneakers.setLayout(panelSneakersLayout);
        panelSneakersLayout.setHorizontalGroup(
            panelSneakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSneakersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTandaWarna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sneakers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSneakersLayout.setVerticalGroup(
            panelSneakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTandaWarna3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sneakers, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelFlatshoes.setBackground(new java.awt.Color(255, 255, 255));
        panelFlatshoes.setRadiusBottomLeft(10);
        panelFlatshoes.setRadiusBottomRight(10);
        panelFlatshoes.setRadiusTopLeft(10);
        panelFlatshoes.setRadiusTopRight(10);
        panelFlatshoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFlatshoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFlatshoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFlatshoesMouseExited(evt);
            }
        });

        panelTandaWarna4.setBackground(new java.awt.Color(25, 150, 202));
        panelTandaWarna4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTandaWarna4Layout = new javax.swing.GroupLayout(panelTandaWarna4);
        panelTandaWarna4.setLayout(panelTandaWarna4Layout);
        panelTandaWarna4Layout.setHorizontalGroup(
            panelTandaWarna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelTandaWarna4Layout.setVerticalGroup(
            panelTandaWarna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        flatshoes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        flatshoes.setForeground(new java.awt.Color(25, 150, 202));
        flatshoes.setText("Flatshoes");
        flatshoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelFlatshoesLayout = new javax.swing.GroupLayout(panelFlatshoes);
        panelFlatshoes.setLayout(panelFlatshoesLayout);
        panelFlatshoesLayout.setHorizontalGroup(
            panelFlatshoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlatshoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTandaWarna4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flatshoes, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFlatshoesLayout.setVerticalGroup(
            panelFlatshoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTandaWarna4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flatshoes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelHeels.setBackground(new java.awt.Color(255, 255, 255));
        panelHeels.setRadiusBottomLeft(10);
        panelHeels.setRadiusBottomRight(10);
        panelHeels.setRadiusTopLeft(10);
        panelHeels.setRadiusTopRight(10);
        panelHeels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHeelsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHeelsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHeelsMouseExited(evt);
            }
        });

        panelTandaWarna5.setBackground(new java.awt.Color(25, 150, 202));
        panelTandaWarna5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTandaWarna5Layout = new javax.swing.GroupLayout(panelTandaWarna5);
        panelTandaWarna5.setLayout(panelTandaWarna5Layout);
        panelTandaWarna5Layout.setHorizontalGroup(
            panelTandaWarna5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelTandaWarna5Layout.setVerticalGroup(
            panelTandaWarna5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        heels.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        heels.setForeground(new java.awt.Color(25, 150, 202));
        heels.setText("Heels");
        heels.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelHeelsLayout = new javax.swing.GroupLayout(panelHeels);
        panelHeels.setLayout(panelHeelsLayout);
        panelHeelsLayout.setHorizontalGroup(
            panelHeelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTandaWarna5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHeelsLayout.setVerticalGroup(
            panelHeelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTandaWarna5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(heels, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelCustom8.setBackground(new java.awt.Color(183, 0, 0));
        jPanelCustom8.setRadiusBottomLeft(20);
        jPanelCustom8.setRadiusBottomRight(20);
        jPanelCustom8.setRadiusTopLeft(20);
        jPanelCustom8.setRadiusTopRight(20);
        jPanelCustom8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom8MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Logout");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom8Layout = new javax.swing.GroupLayout(jPanelCustom8);
        jPanelCustom8.setLayout(jPanelCustom8Layout);
        jPanelCustom8Layout.setHorizontalGroup(
            jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom8Layout.setVerticalGroup(
            jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRunning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPantofel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSneakers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFlatshoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHeels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRunning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPantofel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSneakers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFlatshoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelHeels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jPanelCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panelKiri, java.awt.BorderLayout.LINE_START);

        panelKanan.setBackground(new java.awt.Color(255, 255, 255));
        panelKanan.setLayout(new java.awt.BorderLayout());

        bar.setBackground(new java.awt.Color(25, 150, 202));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/shopping_cart_50dp_E3E3E3.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/history_50dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(920, Short.MAX_VALUE))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelKanan.add(bar, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));
        panelUtama.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        homePage.setBackground(new java.awt.Color(255, 255, 255));
        homePage.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1018, 300));

        jLabelCustom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panjang.png"))); // NOI18N
        jLabelCustom1.setRadius(40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        homePage.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom2.setRadiusBottomLeft(40);
        jPanelCustom2.setRadiusBottomRight(40);
        jPanelCustom2.setRadiusTopLeft(40);
        jPanelCustom2.setRadiusTopRight(40);
        jPanelCustom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom2MouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/running.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 150, 202));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Running");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCustom3.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom3.setRadiusBottomLeft(20);
        jPanelCustom3.setRadiusBottomRight(20);
        jPanelCustom3.setRadiusTopLeft(20);
        jPanelCustom3.setRadiusTopRight(20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Kategori Sepatu");

        javax.swing.GroupLayout jPanelCustom3Layout = new javax.swing.GroupLayout(jPanelCustom3);
        jPanelCustom3.setLayout(jPanelCustom3Layout);
        jPanelCustom3Layout.setHorizontalGroup(
            jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom3Layout.setVerticalGroup(
            jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCustom4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom4.setRadiusBottomLeft(40);
        jPanelCustom4.setRadiusBottomRight(40);
        jPanelCustom4.setRadiusTopLeft(40);
        jPanelCustom4.setRadiusTopRight(40);
        jPanelCustom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/pantofel.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 150, 202));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pantofel");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom4Layout = new javax.swing.GroupLayout(jPanelCustom4);
        jPanelCustom4.setLayout(jPanelCustom4Layout);
        jPanelCustom4Layout.setHorizontalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom4Layout.setVerticalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCustom5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom5.setRadiusBottomLeft(40);
        jPanelCustom5.setRadiusBottomRight(40);
        jPanelCustom5.setRadiusTopLeft(40);
        jPanelCustom5.setRadiusTopRight(40);
        jPanelCustom5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom5MouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/sneakers.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 150, 202));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sneakers");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom5Layout = new javax.swing.GroupLayout(jPanelCustom5);
        jPanelCustom5.setLayout(jPanelCustom5Layout);
        jPanelCustom5Layout.setHorizontalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom5Layout.setVerticalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCustom6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom6.setRadiusBottomLeft(40);
        jPanelCustom6.setRadiusBottomRight(40);
        jPanelCustom6.setRadiusTopLeft(40);
        jPanelCustom6.setRadiusTopRight(40);
        jPanelCustom6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom6MouseExited(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/flatshoes.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 150, 202));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Flatshoes");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom6Layout = new javax.swing.GroupLayout(jPanelCustom6);
        jPanelCustom6.setLayout(jPanelCustom6Layout);
        jPanelCustom6Layout.setHorizontalGroup(
            jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom6Layout.setVerticalGroup(
            jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCustom7.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom7.setRadiusBottomLeft(40);
        jPanelCustom7.setRadiusBottomRight(40);
        jPanelCustom7.setRadiusTopLeft(40);
        jPanelCustom7.setRadiusTopRight(40);
        jPanelCustom7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom7MouseExited(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/heelss.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 150, 202));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Heels");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom7Layout = new javax.swing.GroupLayout(jPanelCustom7);
        jPanelCustom7.setLayout(jPanelCustom7Layout);
        jPanelCustom7Layout.setHorizontalGroup(
            jPanelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom7Layout.setVerticalGroup(
            jPanelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        homePage.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.add(homePage, "card2");

        panelUtama.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKanan.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelKanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    ImageController ic = new ImageController();


    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ShoppingCart shoppingCart = new ShoppingCart();
        panelUtama.removeAll();
        panelUtama.add(shoppingCart);
        panelUtama.repaint();
        panelUtama.revalidate();
        shoppingCart.refreshShoppingCart();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void panelRunningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRunningMouseClicked
        SepatuRunning sepatuRunning = new SepatuRunning();
        panelRunning.setBackground(new Color(245, 141, 63));
        panelTandaWarna1.setBackground(new Color(255, 255, 255));

        panelUtama.removeAll();
        panelUtama.add(sepatuRunning);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelRunningMouseClicked

    private void panelRunningMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRunningMouseEntered
        ic.panelBackgroundEntered(panelRunning, panelTandaWarna1, running);
    }//GEN-LAST:event_panelRunningMouseEntered

    private void panelRunningMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRunningMouseExited
        ic.panelBackgroundExited(panelRunning, panelTandaWarna1, running);
    }//GEN-LAST:event_panelRunningMouseExited

    private void panelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseEntered
        ic.panelBackgroundEntered(panelHome, panelTandaWarna, homeButton);
    }//GEN-LAST:event_panelHomeMouseEntered

    private void panelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseExited
        ic.panelBackgroundExited(panelHome, panelTandaWarna, homeButton);
    }//GEN-LAST:event_panelHomeMouseExited

    private void panelPantofelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPantofelMouseEntered
        ic.panelBackgroundEntered(panelPantofel, panelTandaWarna2, pantofel);
    }//GEN-LAST:event_panelPantofelMouseEntered

    private void panelPantofelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPantofelMouseExited
        ic.panelBackgroundExited(panelPantofel, panelTandaWarna2, pantofel);
    }//GEN-LAST:event_panelPantofelMouseExited

    private void panelSneakersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSneakersMouseEntered
        ic.panelBackgroundEntered(panelSneakers, panelTandaWarna3, sneakers);
    }//GEN-LAST:event_panelSneakersMouseEntered

    private void panelSneakersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSneakersMouseExited
        ic.panelBackgroundExited(panelSneakers, panelTandaWarna3, sneakers);
    }//GEN-LAST:event_panelSneakersMouseExited

    private void panelFlatshoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFlatshoesMouseEntered
        ic.panelBackgroundEntered(panelFlatshoes, panelTandaWarna4, flatshoes);
    }//GEN-LAST:event_panelFlatshoesMouseEntered

    private void panelFlatshoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFlatshoesMouseExited
        ic.panelBackgroundExited(panelFlatshoes, panelTandaWarna4, flatshoes);
    }//GEN-LAST:event_panelFlatshoesMouseExited

    private void panelHeelsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeelsMouseEntered
        ic.panelBackgroundEntered(panelHeels, panelTandaWarna5, heels);
    }//GEN-LAST:event_panelHeelsMouseEntered

    private void panelHeelsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeelsMouseExited
        ic.panelBackgroundExited(panelHeels, panelTandaWarna5, heels);
    }//GEN-LAST:event_panelHeelsMouseExited

    private void panelPantofelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPantofelMouseClicked
        SepatuPantofel sepatuPantofel = new SepatuPantofel();
        panelPantofel.setBackground(new Color(245, 141, 63));
        panelTandaWarna2.setBackground(new Color(255, 255, 255));

        panelUtama.removeAll();
        panelUtama.add(sepatuPantofel);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelPantofelMouseClicked

    private void panelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseClicked
        panelUtama.removeAll();
        panelUtama.add(homePage);
        jPanelCustom2MouseExited(evt);
        jPanelCustom4MouseExited(evt);
        jPanelCustom5MouseExited(evt);
        jPanelCustom6MouseExited(evt);
        jPanelCustom7MouseExited(evt);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelHomeMouseClicked

    private void jPanelCustom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom2MouseEntered
        ic.panelKategoriBackgroundEntered(jPanelCustom2, jLabel8);
    }//GEN-LAST:event_jPanelCustom2MouseEntered

    private void jPanelCustom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom2MouseExited
        ic.panelKategoriBackgroundExited(jPanelCustom2, jLabel8);
    }//GEN-LAST:event_jPanelCustom2MouseExited

    private void jPanelCustom4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseEntered
        ic.panelKategoriBackgroundEntered(jPanelCustom4, jLabel10);
    }//GEN-LAST:event_jPanelCustom4MouseEntered

    private void jPanelCustom4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseExited
        ic.panelKategoriBackgroundExited(jPanelCustom4, jLabel10);
    }//GEN-LAST:event_jPanelCustom4MouseExited

    private void jPanelCustom5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom5MouseEntered
        ic.panelKategoriBackgroundEntered(jPanelCustom5, jLabel12);
    }//GEN-LAST:event_jPanelCustom5MouseEntered

    private void jPanelCustom5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom5MouseExited
        ic.panelKategoriBackgroundExited(jPanelCustom5, jLabel12);
    }//GEN-LAST:event_jPanelCustom5MouseExited

    private void jPanelCustom6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom6MouseEntered
        ic.panelKategoriBackgroundEntered(jPanelCustom6, jLabel14);
    }//GEN-LAST:event_jPanelCustom6MouseEntered

    private void jPanelCustom6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom6MouseExited
        ic.panelKategoriBackgroundExited(jPanelCustom6, jLabel14);
    }//GEN-LAST:event_jPanelCustom6MouseExited

    private void jPanelCustom7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom7MouseEntered
        ic.panelKategoriBackgroundEntered(jPanelCustom7, jLabel16);
    }//GEN-LAST:event_jPanelCustom7MouseEntered

    private void jPanelCustom7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom7MouseExited
        ic.panelKategoriBackgroundExited(jPanelCustom7, jLabel16);
    }//GEN-LAST:event_jPanelCustom7MouseExited

    private void jPanelCustom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseClicked
        SepatuPantofel sepatuPantofel = new SepatuPantofel();
        jPanelCustom4.setBackground(new Color(245, 141, 63));
        jLabel8.setBackground(new Color(255, 255, 255));

        panelUtama.removeAll();
        panelUtama.add(sepatuPantofel);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_jPanelCustom4MouseClicked

    private void jPanelCustom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom2MouseClicked
        SepatuRunning sepatuRunning = new SepatuRunning();
        jPanelCustom2.setBackground(new Color(245, 141, 63));
        jLabel10.setBackground(new Color(255, 255, 255));

        panelUtama.removeAll();
        panelUtama.add(sepatuRunning);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_jPanelCustom2MouseClicked

    private void jPanelCustom8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom8MouseClicked
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jPanelCustom8MouseClicked

    private void jPanelCustom8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom8MouseEntered
        jPanelCustom8.setBackground(new Color(215,20,61));
    }//GEN-LAST:event_jPanelCustom8MouseEntered

    private void jPanelCustom8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom8MouseExited
        jPanelCustom8.setBackground(new Color(183,0,0));
    }//GEN-LAST:event_jPanelCustom8MouseExited

    private void panelSneakersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSneakersMouseClicked
        SepatuSneakers sepatuSneakers = new SepatuSneakers();
        panelSneakers.setBackground(new Color(245, 141, 63));
        panelTandaWarna3.setBackground(new Color(255, 255, 255));
        
        panelUtama.removeAll();
        panelUtama.add(sepatuSneakers);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelSneakersMouseClicked

    private void jPanelCustom5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom5MouseClicked
        SepatuSneakers sepatuSneakers = new SepatuSneakers();
        jPanelCustom5.setBackground(new Color(245, 141, 63));
        jLabel12.setBackground(new Color(255, 255, 255));
        
        panelUtama.removeAll();
        panelUtama.add(sepatuSneakers);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_jPanelCustom5MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        HistoryList historyList = new HistoryList();
        panelUtama.removeAll();
        panelUtama.add(historyList);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void panelFlatshoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFlatshoesMouseClicked
        FlatShoes flatShoes = new FlatShoes();
        panelFlatshoes.setBackground(new Color(245, 141, 63));
        panelTandaWarna4.setBackground(new Color(255, 255, 255));
        
        panelUtama.removeAll();
        panelUtama.add(flatShoes);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelFlatshoesMouseClicked

    private void panelHeelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeelsMouseClicked
        Heels heels = new Heels();
        panelHeels.setBackground(new Color(245, 141, 63));
        panelTandaWarna5.setBackground(new Color(255, 255, 255));
        
        panelUtama.removeAll();
        panelUtama.add(heels);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelHeelsMouseClicked

    private void jPanelCustom6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom6MouseClicked
        FlatShoes flatShoes = new FlatShoes();
        jPanelCustom6.setBackground(new Color(245, 141, 63));
        jLabel14.setBackground(new Color(255, 255, 255));
        
        panelUtama.removeAll();
        panelUtama.add(flatShoes);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_jPanelCustom6MouseClicked

    private void jPanelCustom7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom7MouseClicked
        Heels heels = new Heels();
        jPanelCustom7.setBackground(new Color(245, 141, 63));
        jLabel16.setBackground(new Color(255, 255, 255));
        
        panelUtama.removeAll();
        panelUtama.add(heels);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_jPanelCustom7MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JLabel flatshoes;
    private javax.swing.JLabel heels;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private View.Custom.JLabelCustom jLabelCustom1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private View.Custom.JPanelCustom jPanelCustom1;
    private View.Custom.JPanelCustom jPanelCustom2;
    private View.Custom.JPanelCustom jPanelCustom3;
    private View.Custom.JPanelCustom jPanelCustom4;
    private View.Custom.JPanelCustom jPanelCustom5;
    private View.Custom.JPanelCustom jPanelCustom6;
    private View.Custom.JPanelCustom jPanelCustom7;
    private View.Custom.JPanelCustom jPanelCustom8;
    private View.Custom.JPanelCustom panelFlatshoes;
    private View.Custom.JPanelCustom panelHeels;
    private View.Custom.JPanelCustom panelHome;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private View.Custom.JPanelCustom panelPantofel;
    private View.Custom.JPanelCustom panelRunning;
    private View.Custom.JPanelCustom panelSneakers;
    private javax.swing.JPanel panelTandaWarna;
    private javax.swing.JPanel panelTandaWarna1;
    private javax.swing.JPanel panelTandaWarna2;
    private javax.swing.JPanel panelTandaWarna3;
    private javax.swing.JPanel panelTandaWarna4;
    private javax.swing.JPanel panelTandaWarna5;
    public static javax.swing.JPanel panelUtama;
    private javax.swing.JLabel pantofel;
    private javax.swing.JLabel running;
    private javax.swing.JLabel sneakers;
    // End of variables declaration//GEN-END:variables
}
