/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Control.ImageController;
import Control.ItemController;

/**
 *
 * @author Edward
 */
public class SepatuRunning extends javax.swing.JPanel {

    /**
     * Creates new form FirstItemPage
     */
    public SepatuRunning() {
        initComponents();
        itemController.setLabelJumlahTerjual("Ortuseight Hyperblast", jLabel6);
        itemController.setLabelJumlahTerjual("Kenzo Run", jLabel12);
        itemController.setLabelJumlahTerjual("Brooks Ghost 16", jLabel21);
        itemController.setLabelJumlahTerjual("XPREME", jLabel22);
        
        itemController.showJumlahItem(jLabel5, "Ortuseight Hyperblast");
        itemController.showJumlahItem(jLabel17, "Kenzo Run");
        itemController.showJumlahItem(jLabel19, "Brooks Ghost 16");
        itemController.showJumlahItem(jLabel24, "XPREME");
    }
    
//    public void resizedImage() {
//        
//        ic.ImageResizer(
//                "D:\\Tugas Kuliah\\Sem 3\\Pemrograman Berorientasi Objek\\Tugas\\Tugas UAS\\Ecommerce\\src\\main\\resources\\logo\\add_shopping_cart_1000dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.png", 
//                jLabel6
//        );
//        
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanelCustom12 = new View.Custom.JPanelCustom();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabelCustom9 = new View.Custom.JLabelCustom();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCustom2 = new View.Custom.JPanelCustom();
        jLabel8 = new javax.swing.JLabel();
        jPanelCustom4 = new View.Custom.JPanelCustom();
        jLabel9 = new javax.swing.JLabel();
        jPanelCustom17 = new View.Custom.JPanelCustom();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelCustom13 = new View.Custom.JPanelCustom();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabelCustom10 = new View.Custom.JLabelCustom();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCustom5 = new View.Custom.JPanelCustom();
        jLabel10 = new javax.swing.JLabel();
        jPanelCustom6 = new View.Custom.JPanelCustom();
        jLabel11 = new javax.swing.JLabel();
        jPanelCustom18 = new View.Custom.JPanelCustom();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanelCustom15 = new View.Custom.JPanelCustom();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabelCustom12 = new View.Custom.JLabelCustom();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelCustom8 = new View.Custom.JPanelCustom();
        jLabel13 = new javax.swing.JLabel();
        jPanelCustom9 = new View.Custom.JPanelCustom();
        jLabel14 = new javax.swing.JLabel();
        jPanelCustom19 = new View.Custom.JPanelCustom();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanelCustom16 = new View.Custom.JPanelCustom();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabelCustom13 = new View.Custom.JLabelCustom();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelCustom10 = new View.Custom.JPanelCustom();
        jLabel15 = new javax.swing.JLabel();
        jPanelCustom11 = new View.Custom.JPanelCustom();
        jLabel16 = new javax.swing.JLabel();
        jPanelCustom21 = new View.Custom.JPanelCustom();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanelCustom1 = new View.Custom.JPanelCustom();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1018, 600));
        setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1018, 600));
        jPanel3.setRequestFocusEnabled(false);

        jPanelCustom12.setBackground(new java.awt.Color(34, 34, 34));
        jPanelCustom12.setRadiusBottomLeft(20);
        jPanelCustom12.setRadiusBottomRight(20);
        jPanelCustom12.setRadiusTopLeft(20);
        jPanelCustom12.setRadiusTopRight(20);

        jLabel33.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Ortuseight Hyperblast");

        jLabel34.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Rp 584.565");

        jLabelCustom9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustom9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ortuseight_Hyperblast_c1e9590921 resize.jpg"))); // NOI18N

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Indonesia Running");

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Terjual");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/star_16dp_FFFF55.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanelCustom2.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom2.setRadiusBottomLeft(20);
        jPanelCustom2.setRadiusBottomRight(20);
        jPanelCustom2.setRadiusTopLeft(20);
        jPanelCustom2.setRadiusTopRight(20);
        jPanelCustom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom2MouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("+");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom4.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom4.setRadiusBottomLeft(20);
        jPanelCustom4.setRadiusBottomRight(20);
        jPanelCustom4.setRadiusTopLeft(20);
        jPanelCustom4.setRadiusTopRight(20);
        jPanelCustom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("-");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom4Layout = new javax.swing.GroupLayout(jPanelCustom4);
        jPanelCustom4.setLayout(jPanelCustom4Layout);
        jPanelCustom4Layout.setHorizontalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom4Layout.setVerticalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom17.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom17.setRadiusBottomLeft(10);
        jPanelCustom17.setRadiusBottomRight(10);
        jPanelCustom17.setRadiusTopLeft(10);
        jPanelCustom17.setRadiusTopRight(10);

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("In Cart : ");

        javax.swing.GroupLayout jPanelCustom17Layout = new javax.swing.GroupLayout(jPanelCustom17);
        jPanelCustom17.setLayout(jPanelCustom17Layout);
        jPanelCustom17Layout.setHorizontalGroup(
            jPanelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom17Layout.setVerticalGroup(
            jPanelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");

        javax.swing.GroupLayout jPanelCustom12Layout = new javax.swing.GroupLayout(jPanelCustom12);
        jPanelCustom12.setLayout(jPanelCustom12Layout);
        jPanelCustom12Layout.setHorizontalGroup(
            jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom12Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom12Layout.createSequentialGroup()
                                .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelCustom12Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelCustom12Layout.createSequentialGroup()
                                        .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelCustom17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6))))
                    .addComponent(jLabelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCustom12Layout.setVerticalGroup(
            jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom12Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom12Layout.createSequentialGroup()
                        .addComponent(jPanelCustom17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCustom12Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(jLabel1))))
                    .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanelCustom13.setBackground(new java.awt.Color(34, 34, 34));
        jPanelCustom13.setRadiusBottomLeft(20);
        jPanelCustom13.setRadiusBottomRight(20);
        jPanelCustom13.setRadiusTopLeft(20);
        jPanelCustom13.setRadiusTopRight(20);

        jLabel37.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Kenzo Run");

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Rp 518.420");

        jLabelCustom10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustom10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kenzo_Run_31c323e0f8.jpg"))); // NOI18N

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Indonesia Running");

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Terjual");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/star_16dp_FFFF55.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanelCustom5.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom5.setRadiusBottomLeft(20);
        jPanelCustom5.setRadiusBottomRight(20);
        jPanelCustom5.setRadiusTopLeft(20);
        jPanelCustom5.setRadiusTopRight(20);
        jPanelCustom5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom5MouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("+");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom5Layout = new javax.swing.GroupLayout(jPanelCustom5);
        jPanelCustom5.setLayout(jPanelCustom5Layout);
        jPanelCustom5Layout.setHorizontalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom5Layout.setVerticalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom6.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom6.setRadiusBottomLeft(20);
        jPanelCustom6.setRadiusBottomRight(20);
        jPanelCustom6.setRadiusTopLeft(20);
        jPanelCustom6.setRadiusTopRight(20);
        jPanelCustom6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom6MouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom6Layout = new javax.swing.GroupLayout(jPanelCustom6);
        jPanelCustom6.setLayout(jPanelCustom6Layout);
        jPanelCustom6Layout.setHorizontalGroup(
            jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom6Layout.setVerticalGroup(
            jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom18.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom18.setRadiusBottomLeft(10);
        jPanelCustom18.setRadiusBottomRight(10);
        jPanelCustom18.setRadiusTopLeft(10);
        jPanelCustom18.setRadiusTopRight(10);

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("0");

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("In Cart : ");

        javax.swing.GroupLayout jPanelCustom18Layout = new javax.swing.GroupLayout(jPanelCustom18);
        jPanelCustom18.setLayout(jPanelCustom18Layout);
        jPanelCustom18Layout.setHorizontalGroup(
            jPanelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom18Layout.setVerticalGroup(
            jPanelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("-");

        javax.swing.GroupLayout jPanelCustom13Layout = new javax.swing.GroupLayout(jPanelCustom13);
        jPanelCustom13.setLayout(jPanelCustom13Layout);
        jPanelCustom13Layout.setHorizontalGroup(
            jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom13Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom13Layout.createSequentialGroup()
                                .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelCustom13Layout.createSequentialGroup()
                                        .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelCustom18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCustom13Layout.createSequentialGroup()
                                        .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addGroup(jPanelCustom13Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel40)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6))))
                    .addComponent(jLabelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCustom13Layout.setVerticalGroup(
            jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom13Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom13Layout.createSequentialGroup()
                        .addComponent(jPanelCustom18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom13Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("YOU SEARCH FOR: RUNNING SHOES");

        jPanelCustom15.setBackground(new java.awt.Color(34, 34, 34));
        jPanelCustom15.setRadiusBottomLeft(20);
        jPanelCustom15.setRadiusBottomRight(20);
        jPanelCustom15.setRadiusTopLeft(20);
        jPanelCustom15.setRadiusTopRight(20);

        jLabel45.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Brooks Ghost 16");

        jLabel46.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Rp 1.399.000");

        jLabelCustom12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustom12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Brooks_Ghost_16_1618766a77.jpg"))); // NOI18N

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Indonesia Running");

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Terjual");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/star_16dp_FFFF55.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jPanelCustom8.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom8.setRadiusBottomLeft(20);
        jPanelCustom8.setRadiusBottomRight(20);
        jPanelCustom8.setRadiusTopLeft(20);
        jPanelCustom8.setRadiusTopRight(20);
        jPanelCustom8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom8MouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("+");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom8Layout = new javax.swing.GroupLayout(jPanelCustom8);
        jPanelCustom8.setLayout(jPanelCustom8Layout);
        jPanelCustom8Layout.setHorizontalGroup(
            jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom8Layout.setVerticalGroup(
            jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom9.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom9.setRadiusBottomLeft(20);
        jPanelCustom9.setRadiusBottomRight(20);
        jPanelCustom9.setRadiusTopLeft(20);
        jPanelCustom9.setRadiusTopRight(20);
        jPanelCustom9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom9MouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("-");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom9Layout = new javax.swing.GroupLayout(jPanelCustom9);
        jPanelCustom9.setLayout(jPanelCustom9Layout);
        jPanelCustom9Layout.setHorizontalGroup(
            jPanelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom9Layout.setVerticalGroup(
            jPanelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom19.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom19.setRadiusBottomLeft(10);
        jPanelCustom19.setRadiusBottomRight(10);
        jPanelCustom19.setRadiusTopLeft(10);
        jPanelCustom19.setRadiusTopRight(10);

        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0");

        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("In Cart : ");

        javax.swing.GroupLayout jPanelCustom19Layout = new javax.swing.GroupLayout(jPanelCustom19);
        jPanelCustom19.setLayout(jPanelCustom19Layout);
        jPanelCustom19Layout.setHorizontalGroup(
            jPanelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom19Layout.setVerticalGroup(
            jPanelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addComponent(jLabel20))
        );

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("-");

        javax.swing.GroupLayout jPanelCustom15Layout = new javax.swing.GroupLayout(jPanelCustom15);
        jPanelCustom15.setLayout(jPanelCustom15Layout);
        jPanelCustom15Layout.setHorizontalGroup(
            jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom15Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom15Layout.createSequentialGroup()
                                .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addGroup(jPanelCustom15Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCustom15Layout.createSequentialGroup()
                                        .addComponent(jPanelCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelCustom19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6))))
                    .addComponent(jLabelCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCustom15Layout.setVerticalGroup(
            jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom15Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom15Layout.createSequentialGroup()
                        .addComponent(jPanelCustom19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCustom15Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel3)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanelCustom16.setBackground(new java.awt.Color(34, 34, 34));
        jPanelCustom16.setRadiusBottomLeft(20);
        jPanelCustom16.setRadiusBottomRight(20);
        jPanelCustom16.setRadiusTopLeft(20);
        jPanelCustom16.setRadiusTopRight(20);

        jLabel49.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("XPREME ");

        jLabel50.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Rp 170.499");

        jLabelCustom13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustom13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xpreme.jpg"))); // NOI18N

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Indonesia Running");

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Terjual");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/star_16dp_FFFF55.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jPanelCustom10.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom10.setRadiusBottomLeft(20);
        jPanelCustom10.setRadiusBottomRight(20);
        jPanelCustom10.setRadiusTopLeft(20);
        jPanelCustom10.setRadiusTopRight(20);
        jPanelCustom10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom10MouseExited(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("+");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom10Layout = new javax.swing.GroupLayout(jPanelCustom10);
        jPanelCustom10.setLayout(jPanelCustom10Layout);
        jPanelCustom10Layout.setHorizontalGroup(
            jPanelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom10Layout.setVerticalGroup(
            jPanelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom11.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom11.setRadiusBottomLeft(20);
        jPanelCustom11.setRadiusBottomRight(20);
        jPanelCustom11.setRadiusTopLeft(20);
        jPanelCustom11.setRadiusTopRight(20);
        jPanelCustom11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom11MouseExited(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("-");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom11Layout = new javax.swing.GroupLayout(jPanelCustom11);
        jPanelCustom11.setLayout(jPanelCustom11Layout);
        jPanelCustom11Layout.setHorizontalGroup(
            jPanelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom11Layout.setVerticalGroup(
            jPanelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCustom21.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom21.setRadiusBottomLeft(10);
        jPanelCustom21.setRadiusBottomRight(10);
        jPanelCustom21.setRadiusTopLeft(10);
        jPanelCustom21.setRadiusTopRight(10);

        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("0");

        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("In Cart : ");

        javax.swing.GroupLayout jPanelCustom21Layout = new javax.swing.GroupLayout(jPanelCustom21);
        jPanelCustom21.setLayout(jPanelCustom21Layout);
        jPanelCustom21Layout.setHorizontalGroup(
            jPanelCustom21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCustom21Layout.setVerticalGroup(
            jPanelCustom21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addComponent(jLabel25))
        );

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");

        javax.swing.GroupLayout jPanelCustom16Layout = new javax.swing.GroupLayout(jPanelCustom16);
        jPanelCustom16.setLayout(jPanelCustom16Layout);
        jPanelCustom16Layout.setHorizontalGroup(
            jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom16Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom16Layout.createSequentialGroup()
                                .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelCustom16Layout.createSequentialGroup()
                                        .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelCustom21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCustom16Layout.createSequentialGroup()
                                        .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addGroup(jPanelCustom16Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel52)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6))))
                    .addComponent(jLabelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCustom16Layout.setVerticalGroup(
            jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom16Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom16Layout.createSequentialGroup()
                        .addComponent(jPanelCustom21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom16Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(jLabel4)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanelCustom1.setBackground(new java.awt.Color(34, 34, 34));
        jPanelCustom1.setRadiusBottomLeft(20);
        jPanelCustom1.setRadiusBottomRight(20);
        jPanelCustom1.setRadiusTopLeft(20);
        jPanelCustom1.setRadiusTopRight(20);

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanelCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCustom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCustom16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        add(jPanel3, "card2");
    }// </editor-fold>//GEN-END:initComponents

   
    ImageController ic = new ImageController();
    ItemController itemController = new ItemController();

    private void jPanelCustom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom2MouseClicked
        ic.backgroundEntered(jPanelCustom2);
        itemController.tambahJumlahItem("Ortuseight Hyperblast", 584565, 1, 584565, jLabel5);
    }//GEN-LAST:event_jPanelCustom2MouseClicked

    private void jPanelCustom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseClicked
        ic.backgroundEntered(jPanelCustom4);
        itemController.kurangJumlahItem("Ortuseight Hyperblast", 584565, this, jLabel5);
    }//GEN-LAST:event_jPanelCustom4MouseClicked

    private void jPanelCustom5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom5MouseClicked
        ic.backgroundEntered(jPanelCustom5);
        itemController.tambahJumlahItem("Kenzo Run", 518420, 1, 518420, jLabel17);
    }//GEN-LAST:event_jPanelCustom5MouseClicked

    private void jPanelCustom6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom6MouseClicked
        ic.backgroundEntered(jPanelCustom6);
        itemController.kurangJumlahItem("Kenzo Run", 518420, this, jLabel17);
    }//GEN-LAST:event_jPanelCustom6MouseClicked

    private void jPanelCustom8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom8MouseClicked
        ic.backgroundEntered(jPanelCustom8);
        itemController.tambahJumlahItem("Brooks Ghost 16", 1399000, 1, 1399000, jLabel19);
    }//GEN-LAST:event_jPanelCustom8MouseClicked

    private void jPanelCustom9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom9MouseClicked
        ic.backgroundEntered(jPanelCustom9);
        itemController.kurangJumlahItem("Brooks Ghost 16", 1399000, this, jLabel19);
    }//GEN-LAST:event_jPanelCustom9MouseClicked

    private void jPanelCustom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom2MouseEntered
        ic.backgroundEntered(jPanelCustom2);
    }//GEN-LAST:event_jPanelCustom2MouseEntered

    private void jPanelCustom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom2MouseExited
        ic.backgroundExited(jPanelCustom2);
    }//GEN-LAST:event_jPanelCustom2MouseExited

    private void jPanelCustom10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom10MouseClicked
        ic.backgroundEntered(jPanelCustom10);
        itemController.tambahJumlahItem("XPREME", 170499, 1, 170499, jLabel24);
    }//GEN-LAST:event_jPanelCustom10MouseClicked

    private void jPanelCustom11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom11MouseClicked
        ic.backgroundEntered(jPanelCustom11);
        itemController.kurangJumlahItem("XPREME", 170499, this, jLabel24);
    }//GEN-LAST:event_jPanelCustom11MouseClicked

    private void jPanelCustom4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseEntered
        ic.backgroundEntered(jPanelCustom4);
    }//GEN-LAST:event_jPanelCustom4MouseEntered

    private void jPanelCustom4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseExited
        ic.backgroundExited(jPanelCustom4);
    }//GEN-LAST:event_jPanelCustom4MouseExited

    private void jPanelCustom5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom5MouseEntered
        ic.backgroundEntered(jPanelCustom5);
    }//GEN-LAST:event_jPanelCustom5MouseEntered

    private void jPanelCustom5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom5MouseExited
        ic.backgroundExited(jPanelCustom5);
    }//GEN-LAST:event_jPanelCustom5MouseExited

    private void jPanelCustom6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom6MouseEntered
        ic.backgroundEntered(jPanelCustom6);
    }//GEN-LAST:event_jPanelCustom6MouseEntered

    private void jPanelCustom6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom6MouseExited
        ic.backgroundExited(jPanelCustom6);
    }//GEN-LAST:event_jPanelCustom6MouseExited

    private void jPanelCustom8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom8MouseEntered
        ic.backgroundEntered(jPanelCustom8);
    }//GEN-LAST:event_jPanelCustom8MouseEntered

    private void jPanelCustom8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom8MouseExited
        ic.backgroundExited(jPanelCustom8);
    }//GEN-LAST:event_jPanelCustom8MouseExited

    private void jPanelCustom9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom9MouseEntered
        ic.backgroundEntered(jPanelCustom9);
    }//GEN-LAST:event_jPanelCustom9MouseEntered

    private void jPanelCustom9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom9MouseExited
        ic.backgroundExited(jPanelCustom9);
    }//GEN-LAST:event_jPanelCustom9MouseExited

    private void jPanelCustom10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom10MouseEntered
        ic.backgroundEntered(jPanelCustom10);
    }//GEN-LAST:event_jPanelCustom10MouseEntered

    private void jPanelCustom10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom10MouseExited
        ic.backgroundExited(jPanelCustom10);
    }//GEN-LAST:event_jPanelCustom10MouseExited

    private void jPanelCustom11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom11MouseEntered
        ic.backgroundEntered(jPanelCustom11);
    }//GEN-LAST:event_jPanelCustom11MouseEntered

    private void jPanelCustom11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom11MouseExited
        ic.backgroundExited(jPanelCustom11);
    }//GEN-LAST:event_jPanelCustom11MouseExited

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private View.Custom.JLabelCustom jLabelCustom10;
    private View.Custom.JLabelCustom jLabelCustom12;
    private View.Custom.JLabelCustom jLabelCustom13;
    private View.Custom.JLabelCustom jLabelCustom9;
    private javax.swing.JPanel jPanel3;
    private View.Custom.JPanelCustom jPanelCustom1;
    private View.Custom.JPanelCustom jPanelCustom10;
    private View.Custom.JPanelCustom jPanelCustom11;
    private View.Custom.JPanelCustom jPanelCustom12;
    private View.Custom.JPanelCustom jPanelCustom13;
    private View.Custom.JPanelCustom jPanelCustom15;
    private View.Custom.JPanelCustom jPanelCustom16;
    private View.Custom.JPanelCustom jPanelCustom17;
    private View.Custom.JPanelCustom jPanelCustom18;
    private View.Custom.JPanelCustom jPanelCustom19;
    private View.Custom.JPanelCustom jPanelCustom2;
    private View.Custom.JPanelCustom jPanelCustom21;
    private View.Custom.JPanelCustom jPanelCustom4;
    private View.Custom.JPanelCustom jPanelCustom5;
    private View.Custom.JPanelCustom jPanelCustom6;
    private View.Custom.JPanelCustom jPanelCustom8;
    private View.Custom.JPanelCustom jPanelCustom9;
    // End of variables declaration//GEN-END:variables
}
