/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Control.ImageController;
import Control.ItemController;
import Control.ShoppingCartController;
import Control.ShoppingCart_db_Controller;
import Model.ShoppingCartModel;
import Model.ItemModel;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Edward
 */
public class ShoppingCart extends javax.swing.JPanel {

    /**
     * Creates new form ShoppingCart
     */
    public ShoppingCart() {
        initComponents();
    }

    ShoppingCartModel shoppingCartModel = new ShoppingCartModel();
    ShoppingCartController shoppingCartController = new ShoppingCartController();
    ShoppingCart_db_Controller db = new ShoppingCart_db_Controller();
    ItemController itemController = new ItemController();
    ImageController ic = new ImageController();
    DecimalFormat df = new DecimalFormat("#,##0.00");

    public void isiShoppingCartTabel() {
        shoppingCartModel.listItem.clear();
        db.selectAllItem(shoppingCartModel);
        String[][] dataTabel = new String[shoppingCartModel.listItem.size()][5];

        int i = 0;

        for (ItemModel item : shoppingCartModel.listItem) {
            dataTabel[i][0] = "" + (i + 1);
            dataTabel[i][1] = item.getNama();
            dataTabel[i][2] = String.valueOf(item.getJumlah());
            dataTabel[i][3] = String.valueOf(item.getHarga());
            dataTabel[i][4] = df.format(item.getTotalHargaItem());

            i++;
        }

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
                dataTabel,
                new String[]{
                    "No.", "Items", "Quantity", "Price", "Total"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    public JTable getCartTable() {
        return cartTable;
    }
    
    public void refreshShoppingCart() {
        isiShoppingCartTabel();
        shoppingCartModel.totalHargaItem.clear();
        db.getTotalHargaCart(shoppingCartModel);
        shoppingCartController.totalHargaCart(shoppingCartModel);
        jLabel4.setText(df.format(shoppingCartModel.getTotalHargaCart()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelCustom1 = new View.Custom.JPanelCustom();
        jLabel2 = new javax.swing.JLabel();
        jPanelCustom2 = new View.Custom.JPanelCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelCustom3 = new View.Custom.JPanelCustom();
        jLabel6 = new javax.swing.JLabel();
        jPanelCustom4 = new View.Custom.JPanelCustom();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1018, 600));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1018, 600));

        cartTable.setBackground(new java.awt.Color(255, 255, 255));
        cartTable.setForeground(new java.awt.Color(0, 0, 0));
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Items", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(0).setResizable(false);
            cartTable.getColumnModel().getColumn(1).setResizable(false);
            cartTable.getColumnModel().getColumn(2).setResizable(false);
            cartTable.getColumnModel().getColumn(3).setResizable(false);
            cartTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 150, 202));
        jLabel1.setText("Shopping Cart");

        jPanelCustom1.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom1.setRadiusBottomLeft(30);
        jPanelCustom1.setRadiusBottomRight(30);
        jPanelCustom1.setRadiusTopLeft(30);
        jPanelCustom1.setRadiusTopRight(30);
        jPanelCustom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHECKOUT");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCustom2.setBackground(new java.awt.Color(245, 141, 63));
        jPanelCustom2.setRadiusBottomLeft(20);
        jPanelCustom2.setRadiusBottomRight(20);
        jPanelCustom2.setRadiusTopLeft(20);
        jPanelCustom2.setRadiusTopRight(20);

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Total :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");

        jPanelCustom3.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom3.setRadiusBottomLeft(20);
        jPanelCustom3.setRadiusBottomRight(20);
        jPanelCustom3.setRadiusTopLeft(20);
        jPanelCustom3.setRadiusTopRight(20);
        jPanelCustom3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom3MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("+");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom3Layout = new javax.swing.GroupLayout(jPanelCustom3);
        jPanelCustom3.setLayout(jPanelCustom3Layout);
        jPanelCustom3Layout.setHorizontalGroup(
            jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );
        jPanelCustom3Layout.setVerticalGroup(
            jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCustom4.setBackground(new java.awt.Color(25, 150, 202));
        jPanelCustom4.setRadiusBottomLeft(20);
        jPanelCustom4.setRadiusBottomRight(20);
        jPanelCustom4.setRadiusTopLeft(20);
        jPanelCustom4.setRadiusTopRight(20);
        jPanelCustom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustom4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCustom4Layout = new javax.swing.GroupLayout(jPanelCustom4);
        jPanelCustom4.setLayout(jPanelCustom4Layout);
        jPanelCustom4Layout.setHorizontalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );
        jPanelCustom4Layout.setVerticalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelCustom2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jPanelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(11, 11, 11))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCustom3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom3MouseClicked
        itemController.tambahSelectItemCart(this, shoppingCartModel, this);
        refreshShoppingCart();
    }//GEN-LAST:event_jPanelCustom3MouseClicked

    private void jPanelCustom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseClicked
        itemController.kurangSelectItemCart(this, shoppingCartModel, this);
        refreshShoppingCart();
    }//GEN-LAST:event_jPanelCustom4MouseClicked

    private void jPanelCustom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom1MouseEntered
        ic.backgroundEntered(jPanelCustom1);
    }//GEN-LAST:event_jPanelCustom1MouseEntered

    private void jPanelCustom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom1MouseExited
        ic.backgroundExited(jPanelCustom1);
    }//GEN-LAST:event_jPanelCustom1MouseExited

    private void jPanelCustom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom1MouseClicked
        if (shoppingCartModel.listItem.size() == 0) {
            JOptionPane.showMessageDialog(this, "Cart kosong, pilih item dahulu. Yuk Belanja!!!");
        } else {
            Checkout checkout = new Checkout();
            MainMenu.panelUtama.removeAll();
            MainMenu.panelUtama.add(checkout);
            MainMenu.panelUtama.repaint();
            MainMenu.panelUtama.revalidate();
        }
    }//GEN-LAST:event_jPanelCustom1MouseClicked

    private void jPanelCustom3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom3MouseEntered
        ic.backgroundEntered(jPanelCustom3);
    }//GEN-LAST:event_jPanelCustom3MouseEntered

    private void jPanelCustom3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom3MouseExited
        ic.backgroundExited(jPanelCustom3);
    }//GEN-LAST:event_jPanelCustom3MouseExited

    private void jPanelCustom4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseEntered
        ic.backgroundEntered(jPanelCustom4);
    }//GEN-LAST:event_jPanelCustom4MouseEntered

    private void jPanelCustom4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustom4MouseExited
        ic.backgroundExited(jPanelCustom4);
    }//GEN-LAST:event_jPanelCustom4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cartTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private View.Custom.JPanelCustom jPanelCustom1;
    private View.Custom.JPanelCustom jPanelCustom2;
    private View.Custom.JPanelCustom jPanelCustom3;
    private View.Custom.JPanelCustom jPanelCustom4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
